---
- name: TNP_restart
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Tomcat,Nodeapp and PD restarting...
      shell: |
        echo "sudo systemctl status tomcat passwd_daemon nodapp_daemon.service"
        sudo systemctl status tomcat passwd_daemon nodapp_daemon.service | grep -B 1 'Active'
      register: command_output

    - name: Display Status of service.
      debug:
        var: command_output.stdout_lines
