---
- name: Get OS and Kernel Details
  hosts: all
  gather_facts: yes

  tasks:
    - name: Display OS Details
      debug:
        var: ansible_facts['distribution']

    - name: Display Kernel Version
      debug:
        var: ansible_facts['kernel']